# RBAC资源配置，用于授予Prometheus Operator访问其他命名空间的权限
# 这些资源需要在couponkill命名空间中创建，以便Prometheus Operator可以访问该命名空间中的服务

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-operator-role
  namespace: couponkill
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-operator-role-binding
  namespace: couponkill
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-operator-role
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring

---
# 如果Prometheus Operator使用ClusterRole，可以创建RoleBinding绑定到ClusterRole
# 这种方式更简单，但权限范围更大
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-cluster-role-binding
  namespace: couponkill
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: monitoring