namespace: couponkill

image:
  registry: registry.example.com/couponkill
  tag: latest

services:
  coupon:
    name: couponkill-coupon-service
    port: 8081
    replicas: 2
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 20
      cpu: 60
  order:
    name: couponkill-order-service
    port: 8082
    replicas: 2
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 20
      cpu: 60
  user:
    name: couponkill-user-service
    port: 8083
    replicas: 1
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      cpu: 60

istio:
  enabled: true
  gateway:
    name: couponkill-gw
    host: couponkill.example.com
    port: 80
    tls: false
