---
- name: Install prerequisites
  ansible.builtin.package:
    name: "{{ (ansible_facts.os_family == 'Debian') | ternary(['ca-certificates','curl','gnupg','apt-transport-https'], ['ca-certificates','curl']) }}"
    state: present

- name: Setup Docker repo on Debian family
  when: ansible_facts.os_family == "Debian"
  block:
    - ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
        apt-get update
      args: { warn: false }

- name: Setup Docker repo on RedHat family
  when: ansible_facts.os_family == "RedHat"
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: "https://download.docker.com/linux/{{ (ansible_facts.distribution | lower).replace('alibabalinux','centos') }}/$releasever/$basearch/stable"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: Install Docker CE
  ansible.builtin.package:
    name: "{{ (docker_enable_compose_plugin | bool) | ternary(['docker-ce','docker-ce-cli','containerd.io','docker-buildx-plugin','docker-compose-plugin'], ['docker-ce','docker-ce-cli','containerd.io','docker-buildx-plugin']) }}"
    state: present

- name: Enable & start docker
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
