spring:
  data:
    redis:
      host: r-bp1fgq38nv4mtbp2b9pd.redis.rds.aliyuncs.com
      port: 6379
      username: master0
      password: Yu20040925@
      lettuce:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 20
          max-wait: 2000ms

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: true
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            namespace: 120
            data-id: couponkill-gateway-sentinel
            data-type: json
            group: SENTINEL_GROUP
            rule-type: flow

rocketmq:
  name-server: 114.55.117.16:9876
  producer:
    group: common-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 1
    max-message-size: 4096
    transaction-listener:
      enabled: true
thread-pool:
  async:
    core-pool-size: 50
    max-pool-size: 100
    queue-capacity: 500
    keep-alive-seconds: 60
    rejected-policy: CALLER_RUNS
  order:
    core-pool-size: 50
    max-pool-size: 100
    queue-capacity: 1000
    thread-name-prefix: "order-async-"
    keep-alive-seconds: 60
    rejected-policy: CALLER_RUNS