server:
  port: 80

spring:
  application:
    name: couponkill-gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
        pool:
          type: elastic
          max-connections: 1000
          acquire-timeout: 1000ms
        channel-option:
          connect-timeout: 5000ms
          read-timeout: 10000ms
          write-timeout: 10000ms
        resolver:
          use-dns: false
          ttl: 60s
      routes:
        - id: coupon-service
          uri: lb://couponkill-coupon-service
          predicates:
            - Path=/coupon/**
          filters:
            - StripPrefix=1
            
        - id: order-service
          uri: lb://couponkill-order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            
        - id: user-service
          uri: lb://couponkill-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

      # 增加全局过滤器配置
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10000
            redis-rate-limiter.burstCapacity: 20000
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/fallback

  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 100
        min-idle: 50
        max-wait: 1000ms
    timeout: 1000ms

# 增加线程池配置
thread:
  pool:
    core-size: 200
    max-size: 800
    queue-capacity: 5000
    keep-alive-seconds: 30

# 增加Hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 50
        sleepWindowInMilliseconds: 2000
        errorThresholdPercentage: 40
  threadpool:
    default:
      coreSize: 200
      maximumSize: 800
      maxQueueSize: 5000
      queueSizeRejectionThreshold: 4000

# 增加Ribbon配置
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug
    reactor:
      netty: info