server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 200
      minimum-idle: 20
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 100
        min-idle: 20
        max-wait: 2000ms
    timeout: 2000ms

# 增加线程池配置
thread:
  pool:
    core-size: 200
    max-size: 400
    queue-capacity: 5000
    keep-alive-seconds: 60

# 增加分库分表配置
spring.shardingsphere.datasource.names: ds0,ds1,ds2,ds3

# 配置四个数据源
spring.shardingsphere.datasource.ds0.jdbc-url: jdbc:mysql://127.0.0.1:3306/coupon_db_0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
spring.shardingsphere.datasource.ds0.username: root
spring.shardingsphere.datasource.ds0.password: 123456
spring.shardingsphere.datasource.ds0.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds0.driver-class-name: com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds0.hikari.maximum-pool-size: 50
spring.shardingsphere.datasource.ds0.hikari.minimum-idle: 20
spring.shardingsphere.datasource.ds0.hikari.connection-timeout: 3000
spring.shardingsphere.datasource.ds0.hikari.idle-timeout: 600000
spring.shardingsphere.datasource.ds0.hikari.max-lifetime: 1800000

spring.shardingsphere.datasource.ds1.jdbc-url: jdbc:mysql://127.0.0.1:3306/coupon_db_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
spring.shardingsphere.datasource.ds1.username: root
spring.shardingsphere.datasource.ds1.password: 123456
spring.shardingsphere.datasource.ds1.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds1.driver-class-name: com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds1.hikari.maximum-pool-size: 50
spring.shardingsphere.datasource.ds1.hikari.minimum-idle: 20
spring.shardingsphere.datasource.ds1.hikari.connection-timeout: 3000
spring.shardingsphere.datasource.ds1.hikari.idle-timeout: 600000
spring.shardingsphere.datasource.ds1.hikari.max-lifetime: 1800000

spring.shardingsphere.datasource.ds2.jdbc-url: jdbc:mysql://127.0.0.1:3306/coupon_db_2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
spring.shardingsphere.datasource.ds2.username: root
spring.shardingsphere.datasource.ds2.password: 123456
spring.shardingsphere.datasource.ds2.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds2.driver-class-name: com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds2.hikari.maximum-pool-size: 50
spring.shardingsphere.datasource.ds2.hikari.minimum-idle: 20
spring.shardingsphere.datasource.ds2.hikari.connection-timeout: 3000
spring.shardingsphere.datasource.ds2.hikari.idle-timeout: 600000
spring.shardingsphere.datasource.ds2.hikari.max-lifetime: 1800000

spring.shardingsphere.datasource.ds3.jdbc-url: jdbc:mysql://127.0.0.1:3306/coupon_db_3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
spring.shardingsphere.datasource.ds3.username: root
spring.shardingsphere.datasource.ds3.password: 123456
spring.shardingsphere.datasource.ds3.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds3.driver-class-name: com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds3.hikari.maximum-pool-size: 50
spring.shardingsphere.datasource.ds3.hikari.minimum-idle: 20
spring.shardingsphere.datasource.ds3.hikari.connection-timeout: 3000
spring.shardingsphere.datasource.ds3.hikari.idle-timeout: 600000
spring.shardingsphere.datasource.ds3.hikari.max-lifetime: 1800000

# 分片规则配置
spring.shardingsphere.rules.sharding.tables.coupon.actual-data-nodes: ds$->{0..3}.coupon_$->{0..15}
spring.shardingsphere.rules.sharding.tables.coupon.table-strategy.standard.sharding-column: shard_index
spring.shardingsphere.rules.sharding.tables.coupon.table-strategy.standard.sharding-algorithm-name: coupon-table-inline
spring.shardingsphere.rules.sharding.tables.coupon.database-strategy.standard.sharding-column: shard_index
spring.shardingsphere.rules.sharding.tables.coupon.database-strategy.standard.sharding-algorithm-name: coupon-db-inline

# 分片算法配置
spring.shardingsphere.rules.sharding.sharding-algorithms.coupon-table-inline.type: INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.coupon-table-inline.props.algorithm-expression: coupon_$->{shard_index % 16}
spring.shardingsphere.rules.sharding.sharding-algorithms.coupon-db-inline.type: INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.coupon-db-inline.props.algorithm-expression: ds$->{shard_index / 16 % 4}

# 广播表配置
spring.shardingsphere.rules.sharding.broadcast-tables: t_config

# 打印sql
spring.shardingsphere.props.sql-show: false
spring.shardingsphere.props.max-connections-size-per-query: 32
spring.shardingsphere.props.check-table-metadata-enabled: false

# 增加Sentinel配置
spring.cloud.sentinel.transport.dashboard: localhost:8080
spring.cloud.sentinel.eager: true
spring.cloud.sentinel.metric.file-single-size: 104857600
spring.cloud.sentinel.metric.file-total-count: 6
spring.cloud.sentinel.block-page: /error

# Feign配置
feign.sentinel.enabled: true
feign.client.config.default.connectTimeout: 5000
feign.client.config.default.readTimeout: 10000
feign.hystrix.enabled: false
feign.compression.request.enabled: true
feign.compression.response.enabled: true
feign.compression.request.mime-types: text/xml,application/xml,application/json
feign.compression.request.min-request-size: 2048

# Hystrix配置
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 20
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
hystrix.command.default.circuitBreaker.errorThresholdPercentage: 50

# Ribbon配置
ribbon.ConnectTimeout: 3000
ribbon.ReadTimeout: 10000
ribbon.MaxAutoRetries: 0
ribbon.MaxAutoRetriesNextServer: 1

logging:
  level:
    com:
      aliyun:
        seckill:
          couponkillcouponservice:
            mapper: warn
    org:
      apache:
        shardingsphere: warn
    io:
      letture:
        core:
          protocol: warn