server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-idle: 25
        min-idle: 10
        max-wait: 2000ms
    timeout: 2000ms

# 增加线程池配置
thread:
  pool:
    core-size: 50
    max-size: 200
    queue-capacity: 1000
    keep-alive-seconds: 60

# 增加分库分表配置
spring.shardingsphere.datasource.names: ds0,ds1

# 配置两个数据源
spring.shardingsphere.datasource.ds0.jdbc-url: jdbc:mysql://127.0.0.1:3306/user_db_0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
spring.shardingsphere.datasource.ds0.username: root
spring.shardingsphere.datasource.ds0.password: 123456
spring.shardingsphere.datasource.ds0.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds0.driver-class-name: com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds0.hikari.maximum-pool-size: 25
spring.shardingsphere.datasource.ds0.hikari.minimum-idle: 10
spring.shardingsphere.datasource.ds0.hikari.connection-timeout: 3000
spring.shardingsphere.datasource.ds0.hikari.idle-timeout: 600000
spring.shardingsphere.datasource.ds0.hikari.max-lifetime: 1800000

spring.shardingsphere.datasource.ds1.jdbc-url: jdbc:mysql://127.0.0.1:3306/user_db_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true&useServerPrepStmts=true&cachePrepStmts=true&cacheCallableStmts=true&cacheResultSetMetadata=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
spring.shardingsphere.datasource.ds1.username: root
spring.shardingsphere.datasource.ds1.password: 123456
spring.shardingsphere.datasource.ds1.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.ds1.driver-class-name: com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds1.hikari.maximum-pool-size: 25
spring.shardingsphere.datasource.ds1.hikari.minimum-idle: 10
spring.shardingsphere.datasource.ds1.hikari.connection-timeout: 3000
spring.shardingsphere.datasource.ds1.hikari.idle-timeout: 600000
spring.shardingsphere.datasource.ds1.hikari.max-lifetime: 1800000

# 分片规则配置
spring.shardingsphere.rules.sharding.tables.user.actual-data-nodes: ds$->{0..1}.user
spring.shardingsphere.rules.sharding.tables.user.database-strategy.standard.sharding-column: id
spring.shardingsphere.rules.sharding.tables.user.database-strategy.standard.sharding-algorithm-name: user-db-inline

spring.shardingsphere.rules.sharding.tables.user_coupon_count.actual-data-nodes: ds$->{0..1}.user_coupon_count
spring.shardingsphere.rules.sharding.tables.user_coupon_count.database-strategy.standard.sharding-column: user_id
spring.shardingsphere.rules.sharding.tables.user_coupon_count.database-strategy.standard.sharding-algorithm-name: user-coupon-count-db-inline

# 分片算法配置
spring.shardingsphere.rules.sharding.sharding-algorithms.user-db-inline.type: INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.user-db-inline.props.algorithm-expression: ds$->{id % 2}

spring.shardingsphere.rules.sharding.sharding-algorithms.user-coupon-count-db-inline.type: INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.user-coupon-count-db-inline.props.algorithm-expression: ds$->{user_id % 2}

# 广播表配置
spring.shardingsphere.rules.sharding.broadcast-tables: t_config

# 打印sql
spring.shardingsphere.props.sql-show: false
spring.shardingsphere.props.max-connections-size-per-query: 8
spring.shardingsphere.props.check-table-metadata-enabled: false

# Feign配置
feign.sentinel.enabled: true
feign.client.config.default.connectTimeout: 5000
feign.client.config.default.readTimeout: 10000
feign.hystrix.enabled: false
feign.compression.request.enabled: true
feign.compression.response.enabled: true
feign.compression.request.mime-types: text/xml,application/xml,application/json
feign.compression.request.min-request-size: 2048

# Hystrix配置
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 20
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds: 5000
hystrix.command.default.circuitBreaker.errorThresholdPercentage: 50

# Ribbon配置
ribbon.ConnectTimeout: 3000
ribbon.ReadTimeout: 10000
ribbon.MaxAutoRetries: 0
ribbon.MaxAutoRetriesNextServer: 1

logging:
  level:
    com:
      aliyun:
        seckill:
          couponkilluserservice:
            mapper: warn
    org:
      apache:
        shardingsphere: warn
    io:
      letture:
        core:
          protocol: warn