-- =============================================================================
-- CouponKill PostgreSQL 初始化脚本（MySQL -> PostgreSQL 迁移）
-- 通过 psql 执行： psql -U postgres -h <host> -f init-postgres.sql
--
-- 库表布局与 ShardingSphere 分片规则严格对齐：
--   user  服务 : user_db_0 / user_db_1        -> 表 "user"、user_coupon_count（逻辑表不分表）
--   order 服务 : order_db_0 / order_db_1       -> 表 order_0 .. order_15
--   coupon服务 : coupon_db_0 / coupon_db_1     -> 表 coupon_0 .. coupon_15、stock_log_0 .. stock_log_15
--
-- 字段以 common 模块 POJO + MyBatis Mapper 为唯一真源（不再沿用历史 init.sql 中漂移的字段名）。
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. 创建 6 个分片数据库（幂等）
-- ---------------------------------------------------------------------------
SELECT 'CREATE DATABASE user_db_0'   WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'user_db_0')\gexec
SELECT 'CREATE DATABASE user_db_1'   WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'user_db_1')\gexec
SELECT 'CREATE DATABASE order_db_0'  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'order_db_0')\gexec
SELECT 'CREATE DATABASE order_db_1'  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'order_db_1')\gexec
SELECT 'CREATE DATABASE coupon_db_0' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'coupon_db_0')\gexec
SELECT 'CREATE DATABASE coupon_db_1' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'coupon_db_1')\gexec

-- ---------------------------------------------------------------------------
-- 2. user 服务库表（user_db_0 / user_db_1）
--    "user" 为 PG 保留字，需双引号；create/update_time 由应用显式写入，
--    故无需 MySQL 的 ON UPDATE CURRENT_TIMESTAMP。
-- ---------------------------------------------------------------------------
\c user_db_0

CREATE TABLE IF NOT EXISTS "user" (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username         VARCHAR(50)  NOT NULL UNIQUE,
    password         VARCHAR(100) NOT NULL,
    phone            VARCHAR(20),
    email            VARCHAR(100),
    status           INT          NOT NULL DEFAULT 1,
    create_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    last_active_time TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_coupon_count (
    user_id       BIGINT    NOT NULL,
    total_count   INT       NOT NULL DEFAULT 0,
    seckill_count INT       NOT NULL DEFAULT 0,
    normal_count  INT       NOT NULL DEFAULT 0,
    expired_count INT       NOT NULL DEFAULT 0,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version       INT       NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id)
);

\c user_db_1

CREATE TABLE IF NOT EXISTS "user" (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username         VARCHAR(50)  NOT NULL UNIQUE,
    password         VARCHAR(100) NOT NULL,
    phone            VARCHAR(20),
    email            VARCHAR(100),
    status           INT          NOT NULL DEFAULT 1,
    create_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    last_active_time TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_coupon_count (
    user_id       BIGINT    NOT NULL,
    total_count   INT       NOT NULL DEFAULT 0,
    seckill_count INT       NOT NULL DEFAULT 0,
    normal_count  INT       NOT NULL DEFAULT 0,
    expired_count INT       NOT NULL DEFAULT 0,
    update_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version       INT       NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id)
);

-- ---------------------------------------------------------------------------
-- 3. order 服务库表（order_db_0 / order_db_1，每库 order_0 .. order_15）
--    表名带下划线后缀后不再是保留字；id 为业务生成的字符串（雪花/UUID）。
-- ---------------------------------------------------------------------------
\c order_db_0
DO $$
DECLARE i INT;
BEGIN
    FOR i IN 0..15 LOOP
        EXECUTE format($f$
            CREATE TABLE IF NOT EXISTS order_%s (
                id              VARCHAR(64) NOT NULL,
                user_id         BIGINT      NOT NULL,
                coupon_id       BIGINT      NOT NULL,
                virtual_id      VARCHAR(64) NOT NULL,
                status          INT         NOT NULL DEFAULT 1,
                get_time        TIMESTAMP   NOT NULL,
                expire_time     TIMESTAMP   NOT NULL,
                use_time        TIMESTAMP,
                cancel_time     TIMESTAMP,
                create_time     TIMESTAMP   NOT NULL,
                update_time     TIMESTAMP   NOT NULL,
                created_by_java INT         NOT NULL DEFAULT 0,
                created_by_go   INT         NOT NULL DEFAULT 0,
                request_id      VARCHAR(64) NOT NULL,
                version         INT         NOT NULL DEFAULT 0,
                PRIMARY KEY (id),
                CONSTRAINT uk_order_%s_user_coupon UNIQUE (user_id, coupon_id)
            );
            CREATE INDEX IF NOT EXISTS idx_order_%s_user_id     ON order_%s (user_id);
            CREATE INDEX IF NOT EXISTS idx_order_%s_coupon_id   ON order_%s (coupon_id);
            CREATE INDEX IF NOT EXISTS idx_order_%s_virtual_id  ON order_%s (virtual_id);
            CREATE INDEX IF NOT EXISTS idx_order_%s_create_time ON order_%s (create_time);
        $f$, i, i, i, i, i, i, i, i, i, i);
    END LOOP;

    -- P0 预约帮抢表（单库，配合 ShardingSphere SINGLE → order-db-0）
    CREATE TABLE IF NOT EXISTS seckill_reservation (
        id            BIGSERIAL PRIMARY KEY,
        user_id       BIGINT       NOT NULL,
        coupon_id     BIGINT       NOT NULL,
        status        VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
        reserve_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
        trigger_at    TIMESTAMPTZ,
        fired_at      TIMESTAMPTZ,
        request_id    VARCHAR(64),
        order_id      VARCHAR(64),
        fail_code     INT,
        fail_reason   VARCHAR(256),
        retry_count   INT          NOT NULL DEFAULT 0,
        version       INT          NOT NULL DEFAULT 0,
        create_time   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
        update_time   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    );
    CREATE UNIQUE INDEX IF NOT EXISTS uk_reservation_active_user_coupon
        ON seckill_reservation (user_id, coupon_id)
        WHERE status IN ('PENDING', 'FIRING', 'QUEUED');
    CREATE INDEX IF NOT EXISTS idx_reservation_pending_trigger
        ON seckill_reservation (status, trigger_at)
        WHERE status = 'PENDING';
    CREATE INDEX IF NOT EXISTS idx_reservation_user
        ON seckill_reservation (user_id, create_time DESC);
    CREATE INDEX IF NOT EXISTS idx_reservation_request
        ON seckill_reservation (request_id)
        WHERE request_id IS NOT NULL;

    -- 站内通知（预约结果等；单库 order-db-0）
    CREATE TABLE IF NOT EXISTS user_notification (
        id            BIGSERIAL PRIMARY KEY,
        user_id       BIGINT       NOT NULL,
        type          VARCHAR(64)  NOT NULL,
        title         VARCHAR(128) NOT NULL,
        content       VARCHAR(512),
        ref_id        BIGINT,
        read_flag     BOOLEAN      NOT NULL DEFAULT FALSE,
        create_time   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    );
    CREATE INDEX IF NOT EXISTS idx_notification_user
        ON user_notification (user_id, create_time DESC);
    CREATE INDEX IF NOT EXISTS idx_notification_unread
        ON user_notification (user_id)
        WHERE read_flag = FALSE;
END $$;

\c order_db_1
DO $$
DECLARE i INT;
BEGIN
    FOR i IN 0..15 LOOP
        EXECUTE format($f$
            CREATE TABLE IF NOT EXISTS order_%s (
                id              VARCHAR(64) NOT NULL,
                user_id         BIGINT      NOT NULL,
                coupon_id       BIGINT      NOT NULL,
                virtual_id      VARCHAR(64) NOT NULL,
                status          INT         NOT NULL DEFAULT 1,
                get_time        TIMESTAMP   NOT NULL,
                expire_time     TIMESTAMP   NOT NULL,
                use_time        TIMESTAMP,
                cancel_time     TIMESTAMP,
                create_time     TIMESTAMP   NOT NULL,
                update_time     TIMESTAMP   NOT NULL,
                created_by_java INT         NOT NULL DEFAULT 0,
                created_by_go   INT         NOT NULL DEFAULT 0,
                request_id      VARCHAR(64) NOT NULL,
                version         INT         NOT NULL DEFAULT 0,
                PRIMARY KEY (id),
                CONSTRAINT uk_order_%s_user_coupon UNIQUE (user_id, coupon_id)
            );
            CREATE INDEX IF NOT EXISTS idx_order_%s_user_id     ON order_%s (user_id);
            CREATE INDEX IF NOT EXISTS idx_order_%s_coupon_id   ON order_%s (coupon_id);
            CREATE INDEX IF NOT EXISTS idx_order_%s_virtual_id  ON order_%s (virtual_id);
            CREATE INDEX IF NOT EXISTS idx_order_%s_create_time ON order_%s (create_time);
        $f$, i, i, i, i, i, i, i, i, i, i);
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 4. coupon 服务库表（coupon_db_0 / coupon_db_1）
--    coupon_0 .. coupon_15 与 stock_log_0 .. stock_log_15，均按 shard_index 分片。
--    coupon 复合主键 (id, shard_index)，其 GROUP BY id, shard_index 在 PG 下依赖
--    主键函数依赖成立，SELECT * 合法。
-- ---------------------------------------------------------------------------
\c coupon_db_0
DO $$
DECLARE i INT;
BEGIN
    FOR i IN 0..15 LOOP
        EXECUTE format($f$
            CREATE TABLE IF NOT EXISTS coupon_%s (
                id                     BIGINT        NOT NULL,
                shard_index            INT           NOT NULL,
                name                   VARCHAR(100)  NOT NULL,
                description            TEXT,
                type                   INT           NOT NULL,
                face_value             NUMERIC(10,2),
                min_spend              NUMERIC(10,2) DEFAULT 0.00,
                valid_days             INT           NOT NULL DEFAULT 15,
                per_user_limit         INT           NOT NULL DEFAULT 1,
                total_stock            INT           NOT NULL DEFAULT 0,
                seckill_total_stock    INT           NOT NULL DEFAULT 0,
                remaining_stock        INT           NOT NULL DEFAULT 0,
                seckill_remaining_stock INT          NOT NULL DEFAULT 0,
                status                 INT           NOT NULL DEFAULT 1,
                seckill_start_at       TIMESTAMPTZ,
                seckill_end_at         TIMESTAMPTZ,
                create_time            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                update_time            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                version                INT           NOT NULL DEFAULT 0,
                PRIMARY KEY (id, shard_index)
            );
        $f$, i);
        EXECUTE format($f$
            CREATE TABLE IF NOT EXISTS stock_log_%s (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                coupon_id    BIGINT,
                order_id     BIGINT,
                activity_id  BIGINT,
                quantity     INT,
                operate_type INT,
                operate_id   BIGINT,
                stock_after  INT,
                remark       VARCHAR(255),
                create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                shard_index  INT NOT NULL DEFAULT 0,
                PRIMARY KEY (id, shard_index)
            );
        $f$, i);
    END LOOP;
END $$;

\c coupon_db_1
DO $$
DECLARE i INT;
BEGIN
    FOR i IN 0..15 LOOP
        EXECUTE format($f$
            CREATE TABLE IF NOT EXISTS coupon_%s (
                id                     BIGINT        NOT NULL,
                shard_index            INT           NOT NULL,
                name                   VARCHAR(100)  NOT NULL,
                description            TEXT,
                type                   INT           NOT NULL,
                face_value             NUMERIC(10,2),
                min_spend              NUMERIC(10,2) DEFAULT 0.00,
                valid_days             INT           NOT NULL DEFAULT 15,
                per_user_limit         INT           NOT NULL DEFAULT 1,
                total_stock            INT           NOT NULL DEFAULT 0,
                seckill_total_stock    INT           NOT NULL DEFAULT 0,
                remaining_stock        INT           NOT NULL DEFAULT 0,
                seckill_remaining_stock INT          NOT NULL DEFAULT 0,
                status                 INT           NOT NULL DEFAULT 1,
                seckill_start_at       TIMESTAMPTZ,
                seckill_end_at         TIMESTAMPTZ,
                create_time            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                update_time            TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                version                INT           NOT NULL DEFAULT 0,
                PRIMARY KEY (id, shard_index)
            );
        $f$, i);
        EXECUTE format($f$
            CREATE TABLE IF NOT EXISTS stock_log_%s (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
                coupon_id    BIGINT,
                order_id     BIGINT,
                activity_id  BIGINT,
                quantity     INT,
                operate_type INT,
                operate_id   BIGINT,
                stock_after  INT,
                remark       VARCHAR(255),
                create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                shard_index  INT NOT NULL DEFAULT 0,
                PRIMARY KEY (id, shard_index)
            );
        $f$, i);
    END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- ��¼�����пⲹ UNIQUE(user_id, coupon_id)�����ں��ظ����ݵ���������ֱ��ִ�У�
-- 1) ��ȥ�أ�ÿ�� (user_id, coupon_id) ֻ�������� create_time ��һ��
--      DELETE FROM order_0 a USING order_0 b
--      WHERE a.user_id = b.user_id AND a.coupon_id = b.coupon_id
--        AND a.create_time > b.create_time;
-- 2) �ټ�Լ����
--      ALTER TABLE order_0 ADD CONSTRAINT uk_order_0_user_coupon UNIQUE (user_id, coupon_id);
-- 3) order_db_0 / order_db_1 �� order_0..order_15 ����ִ�У�����ǰ��ر����� dry-run��
-- ---------------------------------------------------------------------------
