apiVersion: apps/v1
kind: Deployment
metadata: {name: {{ .Values.services.user.name }}, namespace: {{ .Values.namespace }}}
spec:
  replicas: {{ .Values.services.user.replicas }}
  selector: {matchLabels: {app: {{ .Values.services.user.name }}}}
  template:
    metadata: {labels: {app: {{ .Values.services.user.name }}}}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.registry }}/user:{{ .Values.image.tag }}"
          ports: [{containerPort: {{ .Values.services.user.port }} }]
          readinessProbe: {httpGet: {path: /actuator/health, port: {{ .Values.services.user.port }}}, initialDelaySeconds: 5, periodSeconds: 10}
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: {name: jwt-secret, key: secret}
---
apiVersion: v1
kind: Service
metadata: {name: {{ .Values.services.user.name }}, namespace: {{ .Values.namespace }}}
spec:
  selector: {app: {{ .Values.services.user.name }}}
  ports: [{port: 80, targetPort: {{ .Values.services.user.port }} }]
---
{{- if .Values.services.user.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: {{ .Values.services.user.name }}, namespace: {{ .Values.namespace }}}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: {{ .Values.services.user.name }}}
  minReplicas: {{ .Values.services.user.hpa.minReplicas }}
  maxReplicas: {{ .Values.services.user.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: {{ .Values.services.user.hpa.cpu }}}
{{- end }}
