apiVersion: apps/v1
kind: Deployment
metadata: {name: {{ .Values.services.coupon.name }}, namespace: {{ .Values.namespace }}}
spec:
  replicas: {{ .Values.services.coupon.replicas }}
  selector: {matchLabels: {app: {{ .Values.services.coupon.name }}}}
  template:
    metadata: {labels: {app: {{ .Values.services.coupon.name }}}}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.registry }}/coupon:{{ .Values.image.tag }}"
          ports: [{containerPort: {{ .Values.services.coupon.port }} }]
          readinessProbe: {httpGet: {path: /actuator/health, port: {{ .Values.services.coupon.port }}}, initialDelaySeconds: 5, periodSeconds: 10}
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: KAFKA
              value: "broker:9092"
---
apiVersion: v1
kind: Service
metadata: {name: {{ .Values.services.coupon.name }}, namespace: {{ .Values.namespace }}}
spec:
  selector: {app: {{ .Values.services.coupon.name }}}
  ports: [{port: 80, targetPort: {{ .Values.services.coupon.port }} }]
---
{{- if .Values.services.coupon.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: {{ .Values.services.coupon.name }}, namespace: {{ .Values.namespace }}}
spec:
  scaleTargetRef: {apiVersion: apps/v1, kind: Deployment, name: {{ .Values.services.coupon.name }}}
  minReplicas: {{ .Values.services.coupon.hpa.minReplicas }}
  maxReplicas: {{ .Values.services.coupon.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {type: Utilization, averageUtilization: {{ .Values.services.coupon.hpa.cpu }}}
{{- end }}
