{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: {name: dr-{{ .Values.services.coupon.name }}, namespace: {{ .Values.namespace }}}
spec:
  host: {{ .Values.services.coupon.name }}
  subsets:
    - name: stable
      labels: { version: stable }
    - name: canary
      labels: { version: canary }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata: {name: dr-{{ .Values.services.order.name }}, namespace: {{ .Values.namespace }}}
spec:
  host: {{ .Values.services.order.name }}
  subsets:
    - name: stable
      labels: { version: stable }
    - name: canary
      labels: { version: canary }
{{- end }}
