# charts/couponkill/templates/keda.yaml
{{- if and .Values.keda.enabled .Values.keda.kafka }}
{{- if .Values.keda.kafka.goEdge.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: so-{{ .Values.keda.kafka.goEdge.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.keda.kafka.goEdge.deploymentName }}  # 关联的Deployment
  pollingInterval: 15  # 检查间隔15秒
  cooldownPeriod: 60  # 冷却时间60秒
  minReplicaCount: {{ .Values.keda.kafka.goEdge.minReplicaCount }}  # 最小副本数
  maxReplicaCount: {{ .Values.keda.kafka.goEdge.maxReplicaCount }}  # 最大副本数
  triggers:
    - type: kafka  # 基于Kafka消息队列触发扩缩容
      metadata:
        bootstrapServers: {{ quote .Values.keda.kafka.bootstrapServers }}
        consumerGroup: {{ .Values.keda.kafka.goEdge.consumerGroup | quote }}
        topic: {{ .Values.keda.kafka.goEdge.topic | quote }}  # 监控的主题
        lagThreshold: {{ .Values.keda.kafka.goEdge.lagThreshold | quote }}  # 消息堆积阈值
---
{{- end }}
{{- if .Values.keda.kafka.order.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: so-{{ .Values.keda.kafka.order.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Values.keda.kafka.order.deploymentName }}  # 订单服务Deployment
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: {{ .Values.keda.kafka.order.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.kafka.order.maxReplicaCount }}
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ quote .Values.keda.kafka.bootstrapServers }}
        consumerGroup: {{ .Values.keda.kafka.order.consumerGroup | quote }}
        topic: {{ .Values.keda.kafka.order.topic | quote }}
        lagThreshold: {{ .Values.keda.kafka.order.lagThreshold | quote }}
{{- end }}
{{- end }}