{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couponkill-monitor
  namespace: {{ .Values.namespaceMonitor }}
  labels:
    app: couponkill
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.go.name }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couponkill-user-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: couponkill-user
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.user.name }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couponkill-order-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: couponkill-order
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.order.name }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couponkill-coupon-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: couponkill-coupon
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.coupon.name }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: couponkill-nacos-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: nacos
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.nacos.name }}
  podMetricsEndpoints:
  - port: nacos-port
    path: /nacos/actuator/prometheus
    interval: 30s
{{- end }}
{{- end }}