apiVersion: v1
kind: Pod
metadata:
  name: software-pod
  namespace: couponkill
  labels:
    app: software
spec:
  imagePullSecrets:
    - name: mysecret
  containers:
    # nacos模块
    - name: nacos
      image: crpi-n5rumpjwbqinoz4c.cn-hangzhou.personal.cr.aliyuncs.com/thetestspacefordocker/my-docker:nacos-server
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      ports:
        - containerPort: 8848
      imagePullPolicy: IfNotPresent
      env:
        - name: MODE
          value: "standalone"
        - name: SPRING_DATASOURCE_PLATFORM
          value: "mysql"
        - name: MYSQL_SERVICE_HOST
          value: "storage-service"
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_DB_NAME
          value: "nacos"
        - name: MYSQL_SERVICE_USER
          value: "root"
        - name: MYSQL_SERVICE_PASSWORD
          value: "123456"
      livenessProbe:
        httpGet:
          path: /nacos/actuator/health
          port: 8848
        initialDelaySeconds: 60
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /nacos/actuator/health
          port: 8848
        initialDelaySeconds: 30
        periodSeconds: 5

    # rocketmq-namesrv模块
    - name: rocketmq-namesrv
      image: crpi-n5rumpjwbqinoz4c.cn-hangzhou.personal.cr.aliyuncs.com/thetestspacefordocker/my-docker:rocketmq-namesrv
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 9876
      imagePullPolicy: IfNotPresent
      env:
        - name: NAMESRV_ADDR
          value: "software-service:9876"
      livenessProbe:
        tcpSocket:
          port: 9876
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 9876
        initialDelaySeconds: 10
        periodSeconds: 5

    # rocketmq-broker模块
    - name: rocketmq-broker
      image: crpi-n5rumpjwbqinoz4c.cn-hangzhou.personal.cr.aliyuncs.com/thetestspacefordocker/my-docker:rocketmq-broker
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      ports:
        - containerPort: 10909
        - containerPort: 10911
        - containerPort: 10912
      imagePullPolicy: IfNotPresent
      env:
        - name: NAMESRV_ADDR
          value: "software-service:9876"
        - name: BROKER_IP1
          value: "software-service"
      livenessProbe:
        tcpSocket:
          port: 10911
        initialDelaySeconds: 60
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 10911
        initialDelaySeconds: 30
        periodSeconds: 5

    # sentinel-dashboard模块
    - name: sentinel-dashboard
      image: crpi-n5rumpjwbqinoz4c.cn-hangzhou.personal.cr.aliyuncs.com/thetestspacefordocker/my-docker:sentinel-dashboard
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5