apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  namespace: couponkill
  labels:
    app: storage
spec:
  imagePullSecrets:
    - name: mysecret
  containers:
    - name: mysql
      image: crpi-n5rumpjwbqinoz4c.cn-hangzhou.personal.cr.aliyuncs.com/thetestspacefordocker/my-docker:mysql
      resources:
        requests:
          memory: "1Gi"
          cpu: "1000m"
        limits:
          memory: "2Gi"
          cpu: "2000m"
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "couponkill"
        - name: MYSQL_USER
          value: "nacos"
        - name: MYSQL_PASSWORD
          value: "nacos"
      volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 60
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 30
        periodSeconds: 5

    - name: redis
      image: crpi-n5rumpjwbqinoz4c.cn-hangzhou.personal.cr.aliyuncs.com/thetestspacefordocker/my-docker:redis
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 6379
      env:
        - name: REDIS_PASSWORD
          value: ""
      volumeMounts:
        - name: redis-storage
          mountPath: /data
      livenessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 6379
        initialDelaySeconds: 10
        periodSeconds: 5

  volumes:
    - name: mysql-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
    - name: redis-storage
      persistentVolumeClaim:
        claimName: redis-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: couponkill
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: couponkill
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: couponkill
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: couponkill
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi