# src/main/resources/application-dev.yml
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/console?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234


  data:
    redis:
      database: 0
      host: localhost
      port: 6379

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aliyun.seckill.pojo
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: aliyun-seckill-coupon-secret-key-123456
  expiration: 86400000  # 24小时

feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: user-service-group