//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package controllers

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeckillScalePolicy) DeepCopyInto(out *SeckillScalePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeckillScalePolicy.
func (in *SeckillScalePolicy) DeepCopy() *SeckillScalePolicy {
	if in == nil {
		return nil
	}
	out := new(SeckillScalePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeckillScalePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeckillScalePolicySpec) DeepCopyInto(out *SeckillScalePolicySpec) {
	*out = *in
	if in.OtherServices != nil {
		in, out := &in.OtherServices, &out.OtherServices
		*out = make([]OtherScale, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeckillScalePolicySpec.
func (in *SeckillScalePolicySpec) DeepCopy() *SeckillScalePolicySpec {
	if in == nil {
		return nil
	}
	out := new(SeckillScalePolicySpec)
	in.DeepCopyInto(out)
	return out
}
