server:
  port: 8080  # 网关端口

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:25000
        port: 8719
      eager: true
      scg:
        fallback:
          mode: response
          response-status: 429
          response-body: "Too Many Requests"
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: couponkill-gateway-sentinel-rules
            groupId: DEFAULT_GROUP
            rule-type: flow
    gateway:
      routes:
        - id: user-service
          uri: lb://couponkill-user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: user-service
                fallbackUri: forward:/fallback/user
                
        - id: coupon-service
          uri: lb://couponkill-coupon-service
          predicates:
            - Path=/coupon/**
          filters:
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: coupon-service
                fallbackUri: forward:/fallback/coupon
                
        - id: order-service
          uri: lb://couponkill-order-service
          predicates:
            - Path=/order/**,/seckill/**
          filters:
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: order-service
                fallbackUri: forward:/fallback/order
                
        - id: seckill-go-service
          uri: lb://seckill-go-svc
          predicates:
            - Path=/seckill/go/**
          filters:
            - StripPrefix=1
            - name: Sentinel
              args:
                resourceName: seckill-go-service
                fallbackUri: forward:/fallback/seckill