server:
  port: 8082

spring:
  application:
    name: couponkill-order-service
seata:
  enabled: true
  application-id: couponkill-order-service
  tx-service-group: couponkill-order-service-tx-group
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 120
      group: DEFAULT_GROUP
      application: seata-server
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 120
      group: DEFAULT_GROUP
# 订单服务专属配置（仅订单服务使用）
rocketmq:
  consumer:
    group:
      seckill-result: seckill-order-result-group  # 订单服务专属消费组
  topic:
    seckill-order-result: seckill.order.result    # 订单服务监听的主题
