server:
  port: 8081

spring:
  application:
    name: couponkill-coupon-service
  
# 优惠券业务配置
coupon:
  publish:
    max-count: 10000  # 单批次最大发布数量（开发环境）
  cache:
    preload: true  # 启动时预加载优惠券到缓存
# JWT配置
jwt:
  secret: mySecretKeyForJWTTokenGenerationWhichShouldBeAtLeast256BitsLong
  expiration: 86400000 # 24小时，单位毫秒
couponkill:
  seckill:
    cooldown-seconds: 2
    deduct-ttl-seconds: 300
seata:
  enabled: true
  application-id: couponkill-coupon-service
  tx-service-group: dev-tx-group
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 120
      group: DEFAULT_GROUP
      application: seata-server
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 120
      group: DEFAULT_GROUP
# 流量控制配置
traffic:
  control:
    threshold: 1000  # Java服务处理阈值，超过则调用Go服务
    go-service:
      enabled: true
      url: http://seckill-go-svc:8090
      timeout: 2000