server:
  port: 8099  # 网关端口

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:25000
        port: 8719
      eager: true
      scg:
        fallback:
          mode: response
          response-status: 429
          response-body: "Too Many Requests"
    gateway:
      # 路由配置（动态调整，无需硬编码在本地文件）
      routes:
        - id: user-service-docs
          uri: lb://couponkill-user-service  # 转发到用户服务
          predicates:
            - Path=/doc.html, /swagger-ui/**, /v3/api-docs/**, /webjars/**, /api/v1/auth/**
          filters:
            # 文档路径不需要去除前缀（保持原样转发）
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: user-service-docs
                fallbackUri: forward:/fallback/user
        - id: user-service
          uri: lb://couponkill-user-service  # 负载均衡到用户服务
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: user-service
                fallbackUri: forward:/fallback/user
                
        - id: coupon-service
          uri: lb://couponkill-coupon-service
          predicates:
            - Path=/coupon/**
          filters:
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: coupon-service
                fallbackUri: forward:/fallback/coupon
                
        - id: order-service
          uri: lb://couponkill-order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: order-service
                fallbackUri: forward:/fallback/order
                
        - id: admin-service
          uri: lb://couponkill-admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=0
            - name: Sentinel
              args:
                resourceName: admin-service
                fallbackUri: forward:/fallback/admin
