openapi: 3.0.3
info:
  title: CouponKill API
  version: 1.1.0
servers:
  - url: /api/v1
paths:
  /seckill/{couponId}/enter:
    post:
      security: [{BearerAuth: []}]
      parameters:
        - in: path
          name: couponId
          required: true
          schema: {type: string}
      responses:
        '200':
          description: queued
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ApiRespEnter'}
  /seckill/results/{requestId}:
    get:
      parameters:
        - in: path
          name: requestId
          required: true
          schema: {type: string}
      responses:
        '200':
          description: result
          content:
            application/json:
              schema: {$ref: '#/components/schemas/ApiRespResult'}
  /auth/token/mock:
    post:
      summary: Issue a short-lived JWT for load testing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId: {type: string}
                roles:
                  type: array
                  items: {type: string}
              required: [userId]
      responses:
        '200':
          description: token
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: {type: integer}
                  message: {type: string}
                  data:
                    type: object
                    properties:
                      tokenType: {type: string}
                      token: {type: string}
                      expiresIn: {type: integer}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ApiRespEnter:
      type: object
      properties:
        code: {type: integer}
        message: {type: string}
        requestId: {type: string}
        data:
          type: object
          properties: {status: {type: string, enum: [QUEUED, REJECTED]}}
    ApiRespResult:
      type: object
      properties:
        code: {type: integer}
        message: {type: string}
        requestId: {type: string}
        data:
          type: object
          properties:
            status: {type: string, enum: [SUCCESS, FAIL, PENDING]}
            orderId: {type: string, nullable: true}
