# Telemetry配置，定义服务网格的遥测策略
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  accessLogging:
    - providers:
      - name: envoy
  metrics:
    - providers:
      - name: prometheus
      reportingInterval: 10s

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: couponkill-telemetry
  namespace: couponkill
spec:
  selector:
    matchLabels:
      app: seckill-go
  accessLogging:
    - providers:
      - name: envoy
      filter:
        expression: response.code >= 400
  metrics:
    - providers:
      - name: prometheus
      overrides:
      - tagOverrides:
          response_code:
            value: "string(response.code)"
          request_operation:
            value: "request.headers['x-request-operation']"
      reportingInterval: 5s

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: order-service-telemetry
  namespace: couponkill
spec:
  selector:
    matchLabels:
      app: couponkill-order-service
  accessLogging:
    - providers:
      - name: envoy
      filter:
        expression: response.code >= 400
  metrics:
    - providers:
      - name: prometheus
      overrides:
      - tagOverrides:
          response_code:
            value: "string(response.code)"
          request_operation:
            value: "request.headers['x-request-operation']"
      reportingInterval: 5s

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: coupon-service-telemetry
  namespace: couponkill
spec:
  selector:
    matchLabels:
      app: couponkill-coupon-service
  accessLogging:
    - providers:
      - name: envoy
      filter:
        expression: response.code >= 400
  metrics:
    - providers:
      - name: prometheus
      overrides:
      - tagOverrides:
          response_code:
            value: "string(response.code)"
          request_operation:
            value: "request.headers['x-request-operation']"
      reportingInterval: 5s

---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: user-service-telemetry
  namespace: couponkill
spec:
  selector:
    matchLabels:
      app: couponkill-user-service
  accessLogging:
    - providers:
      - name: envoy
      filter:
        expression: response.code >= 400
  metrics:
    - providers:
      - name: prometheus
      overrides:
      - tagOverrides:
          response_code:
            value: "string(response.code)"
          request_operation:
            value: "request.headers['x-request-operation']"
      reportingInterval: 5s
