rocketmq:
  # 生产者配置
  producer:
    group: seckill-order-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
  
  # 消费者配置
  consumer:
    group:
      seckill-result: seckill-order-result-group  # 秒杀结果消费组
      order-create: seckill-order-create-group    # 订单创建消费组
  
  # 主题配置
  topic:
    seckill-order-create: seckill_order_create    # 订单创建主题
    seckill-order-result: seckill_order_result    # 订单结果主题
    seckill-compensation: seckill_compensation    # 补偿消息主题
  
  # 重试配置
  retry:
    max-reconsume-times: 3  # 最大重试次数
    delay-level: 3          # 重试延迟级别（1=1s, 3=10s, 5=60s）
