apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: order-service-vs
spec:
  hosts:
    - "*"
  gateways:
    - couponkill-gateway
  http:
    - match:
        - uri:
            prefix: /order
      route:
        - destination:
            host: couponkill-order-service
            port:
              number: 8082
      retries:
        attempts: 1
        perTryTimeout: 2s
      timeout: 10s
