apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: seckill-go-vs
spec:
  hosts:
    - "*"
  gateways:
    - couponkill-gateway
  http:
    - match:
        - uri:
            prefix: /seckill
      route:
        - destination:
            host: seckill-go-svc
            port:
              number: 8090
      retries:
        attempts: 2
        perTryTimeout: 2s
      timeout: 5s
# VirtualService配置文件，用于定义HTTP路由规则和服务网格中的流量管理策略
#
# 参数说明:
# apiVersion: 指定使用的Istio API版本为networking.istio.io/v1beta1
# kind: 资源类型为VirtualService，用于配置虚拟服务
# metadata: 资源元数据配置
#   name: 虚拟服务名称，设置为seckill-go-vs
# spec: 虚拟服务的具体配置规范
#   hosts: 定义服务主机列表，"*"表示匹配所有主机
#   gateways: 指定关联的网关列表，这里使用couponkill-gateway网关
#   http: HTTP路由规则配置数组
#     match: 路由匹配条件配置
#       uri: URI匹配规则
#         prefix: 路径前缀匹配，匹配/seckill开头的请求路径
#     route: 路由目标配置数组
#       destination: 目标服务配置
#         host: 目标服务主机名，指向seckill-go-svc服务
#         port: 目标服务端口配置
#           number: 端口号设置为8090
#     retries: 重试策略配置
#       attempts: 重试次数设置为2次
#       perTryTimeout: 每次重试超时时间设置为2秒
#     timeout: 整体请求超时时间设置为5秒

