# k8s/seckill-go-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seckill-go  # 秒杀服务部署名称
spec:
  replicas: 2  # 初始副本数为2，可通过KEDA自动扩缩容
  selector:
    matchLabels:
      app: seckill-go
  template:
    metadata:
      labels:
        app: seckill-go
    spec:
      containers:
        - name: seckill-go
          image: seckill-go:latest  # Go语言编写的秒杀服务镜像
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090  # 服务端口
---
# 秒杀服务对应的Service配置
apiVersion: v1
kind: Service
metadata:
  name: seckill-go-svc  # 服务名称
spec:
  selector:
    app: seckill-go  # 关联到上面的Deployment
  ports:
    - port: 8090
      targetPort: 8090  # 映射到容器端口