spring:
  datasource:
    url: jdbc:mysql://localhost:3306/console?useSSL=false&characterEncoding=utf8mb4&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.batch_size: 100
couponkill:
  order:
    max-retry: 3
