spring:
  datasource:
    url: jdbc:mysql://116.62.178.91:3306/console?useSSL=false&characterEncoding=utf8mb4&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:4321}
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.batch_size: 100
  sql:
    init:
      mode: never
  main:
    allow-bean-definition-overriding: true