spring:
  datasource:
    url: jdbc:mysql://mysql:3306/console?useSSL=false&characterEncoding=utf8mb4&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.batch_size: 100
  kafka:
    bootstrap-servers: ${KAFKA:broker:9092}
    listener:
      ack-mode: manual
    consumer:
      group-id: order-create
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.couponkill.common.seckill.SeckillOrderCommand
        spring.json.trusted.packages: "*"

couponkill:
  order:
    max-retry: 3
