spring:
  application:
    name: couponkill-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 120
      config:
        server-addr: localhost:8848
        namespace: 120
        group: DEFAULT_GROUP
        file-extension: yaml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aliyun.seckill.common.pojo
# 启用Feign

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
      couponkill-coupon-service:
        connectTimeout: 5000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true
  httpclient:
    enabled: true
  sentinel:
    enabled: true

# 日志配置
logging:
  level:
    com:
      aliyun:
        seckill:
          couponkillorderservice:
            feign: DEBUG

