server:
  port: 8083  # 用户服务开发环境端口

# 服务注册到Nacos的名称（必须与网关路由匹配）
spring:
  application:
    name: couponkill-user-service
  # 用户服务特定配置（如缓存过期时间）
user:
  cache:
    expire: 3600  # 用户信息缓存3600秒
  # 登录相关配置
  login:
    token-expire: 86400  # JWT令牌过期时间（秒）