apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: couponkill-gow-service
    namespace: couponkill
spec:
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: couponkill-go-service