---
- name: Create node_exporter user
  ansible.builtin.user:
    name: node-exp
    system: true
    shell: /usr/sbin/nologin

- name: Download node_exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /opt/
    remote_src: true
    creates: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"

- name: Symlink binary
  ansible.builtin.file:
    src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    state: link
    force: true

- name: Systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=node-exp
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: Restart node_exporter

handlers:
  - name: Restart node_exporter
    ansible.builtin.systemd:
      name: node_exporter
      enabled: true
      state: restarted
      daemon_reload: true
