apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: couponkill-coupon-service
    namespace: couponkill
spec:
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: couponkill-coupon-service
  minReplicas: 2
  metrics:
      - type: Resource
        resource:
            name: cpu
            target: {type: Utilization, averageUtilization: 50}