spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp19518a44a083lmyio.mysql.rds.aliyuncs.com:3306/console?charset=utf8mb4&parseTime=True&loc=Local
    username: master0
    password: Yu20040925@  # 使用环境变量注入密码
    hikari:
      maximum-pool-size: 300
      minimum-idle: 10
      connection-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 60000
  # Redis配置（开发环境）
  data:
    redis:
      host: r-bp1fgq38nv4mtbp2b9pd.redis.rds.aliyuncs.com  # 开发环境应使用本地或局域网地址
      port: 6379
      username: master0
      password: Yu20040925@  # 使用环境变量注入密码
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 2000ms
      # Sentinel配置（开发环境）
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080  # 开发环境Sentinel控制台地址
        port: 8719
      eager: true
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            namespace: 120
            data-id: couponkill-gateway-sentine
            data-type: json
            group: SENTINEL_GROUP
            rule-type: flow

# RocketMQ 配置
rocketmq:
  name-server: 114.55.117.16:9876
  producer:
    group: common-producer-group
    send-message-timeout: 50000
    retry-times-when-send-failed: 2
    # 添加事务生产者配置
    transaction-listener:
      enabled: true

# Seata 公共配置
seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 120
      group: DEFAULT_GROUP
      application: seata-server
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 120
      group: DEFAULT_GROUP
