CREATE TABLE `order_0` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_1` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_2` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_3` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_4` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_5` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_6` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_7` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_8` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_9` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_10` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_11` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_12` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_13` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_14` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_15` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `coupon_id` BIGINT NOT NULL,
  `virtual_id` VARCHAR(64) NOT NULL,
  `status` INT NOT NULL DEFAULT 1 COMMENT '1-已创建,2-已使用,3-已过期,4-已取消',
  `get_time` DATETIME NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `use_time` DATETIME DEFAULT NULL,
  `cancel_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NOT NULL,
  `created_by_java` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `created_by_go` INT NOT NULL DEFAULT 0 COMMENT '0-否,1-是',
  `request_id` VARCHAR(64) NOT NULL,
  `version` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_coupon_id` (`coupon_id`),
  KEY `idx_virtual_id` (`virtual_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_user_coupon_status_cover` (`user_id`, `coupon_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;