server:
  port: 8090

seckill:
  max-concurrency: 2000
  redis-key-prefix: "seckill:"
  valid-days: 7
  redis:
    stock-key-prefix: "coupon:stock:"

mysql:
  dataSources: {}

data.redis:
  host: "localhost:6379"
  username: ""
  password: ""
  db: 0

nacos:
  server-addr: "localhost:8848"
  namespace-id: "120"
