name: CouponKill CI/CD
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Java services
        run: ./mvnw test -f couponkill-coupon-service/pom.xml
      - name: Test Go service
        run: cd couponkill-go-service && go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login -u ${{ secrets.ACR_USERNAME }} --password-stdin ${{ secrets.ACR_REPOSITORY }}
      - name: Build Docker images
        run:
         make build-all-images-registry
         make push-all-images


  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'  # 仅main分支触发生产部署
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Helm Chart version
        run: ./scripts/bump-chart-version.sh  # 自动更新Chart版本
      - name: Push changes
        run: git push origin main  # 触发Argo CD同步